name: educonnect
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  http: ^1.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.12
  shared_preferences: ^2.2.2
  onboarding: ^3.1.0
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  smooth_page_indicator: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.4
flutter_native_splash:
  color: '#ffffff'
  image: assets/logo1.png
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Quantico
      fonts:
        - asset: lib/design/Quantico-Regular.ttf
        - asset: lib/design/Quantico-Bold.ttf
        - asset: lib/design/Quantico-BoldItalic.ttf
        - asset: lib/design/Quantico-Italic.ttf